### ISSUE TITLE
No longer functional after Plazas & Promenades

### ISSUE THREAD

**Issue by amnoah** [ST-Apps/CS-ParallelRoadTool#106]
No long functional after the latest update, all UI options work but the mod cannot place down roads.

**Comment by sabz612damax** [comment]
I have this issue fixed in a fork and can push it back here for you if you like.

**Comment by DoomsdayOrange** [comment]
> I have this issue fixed in a fork and can push it back here for you if you like.

Please do. Even better if you upload it to the steam workshop. I doubt the creator would care

**Comment by sabz612damax** [comment]
@ST-Apps If you want to create a feature branch for this from master, I will complete my pull request so you can review and merge.

**Comment by amnoah** [comment]
> Please do. Even better if you upload it to the steam workshop. I doubt the creator would care

The project is licensed under MIT so it's allowed at the very least.

**Comment by ST-Apps** [comment]
@DoomsdayOrange this is an odd statement considering that I posted a comment on workshop saying that I'm working on a complete rewrite for this mod 🤔 

@sabz612damax feel free to start a PR, the fix should be quite easy but I've been dealing with this rewrite and didn't have enough time unfortunately.

**Comment by sabz612damax** [comment]
@ST-Apps i already have the change in my fork and have a draft change control. Just need to know what branch you would like me to submit to, then I can submit it.

I personally must have missed the post / comment you made - I was thinking about some UI options the other day and was going to play around with a few possible ideas. I still want to look at some other mods and wrap my head around how to arrange things, then I might make some mock-ups to see if I can visualize my ideas a little better. Happy to share the result if you are going to work on any UI.

**Comment by ST-Apps** [comment]
Actually the work is mostly done and is currently being tested in a private beta that I expect to open soon, but any mockup is very welcome since I'm still not a UI person 😄

**Comment by sabz612damax** [comment]
I'm not a "real" designer either, but I do have my moments, lol. Anyhow, what branch would you like the code to go in - dev / master / somewhere else?

**Comment by ST-Apps** [comment]
Please open the PR to master as dev will contain the 3.0 version anytime soon.
