### ISSUE TITLE
Network Skins' settings are not applied

### ISSUE THREAD

**Issue by BadiBasso** [ST-Apps/CS-ParallelRoadTool#12]
When creating networks, settings from Network Skins mod are not applied.

**Comment by BadiBasso** [comment]
Working on this. Seems like detouring issue with some methods.

**Comment by ST-Apps** [comment]
The problem should be in Network Skin's code.
I forked it Yesterday but I didn't have the chance to test my modification.

Changing the `NetManagerDetour` file to add `case "CreateSegmentOriginal":` on line 92 should be enough.
Do you think you can test it?

**Comment by BadiBasso** [comment]
No chance today. Will try to take a look on weekend at the latest. I've already forked Network Skins and a couple of other mods regarding networks to get some insight on detouring.

**Comment by BadiBasso** [comment]
What if Skins' dev is asked for permission to publish the fix as a new mod in beta status?
That way it can be certained that the fix doesn' t break anything from current Skins' users.

**Comment by ST-Apps** [comment]
Yeah, I figured that out after replying, our stacktrace is quite different from the one that Network Skins' is expecting.
I'm quite confident that our modifications won't impact anything else on Network Skins, but I'll have to see with boformer what's the best thing to do in this case.

thanks for your help :)

**Comment by BadiBasso** [comment]
IMO a separate version is not a solution here.
It would only confuse users and keeping it up to date with the original would just create additional work.

**Comment by ST-Apps** [comment]
@BadiBasso do you have a working fork of this? Can you try it and see if it's still working?

**Comment by BadiBasso** [comment]
@ST-Apps Works just fine here, for what I have tested. Have to note that Skins' settings apply to all roads of the same collision type: ground, elevated etc. No way to set them individually by road atm.

**Comment by ST-Apps** [comment]
> No way to set them individually by road atm.
This will never be possible.

If it works, can you please submit a PR to Network Skin's repository?

**Comment by BadiBasso** [comment]
PR: https://github.com/boformer/NetworkSkins/pull/19

**Comment by BadiBasso** [comment]
Any news on boformer?
BTW sent you a Steam friend request; my nic there is leom......i.

**Comment by t1a2l** [comment]
@ST-Apps - I downloaded the Network Skins mod locally, add your lines and run the game and it is working well. I contacted the author and sent him the updated DLL file, he will update it shortly.

**Comment by BadiBasso** [comment]
Network Skins has been updated in the workshop :)

**Comment by BadiBasso** [comment]
>No way to set them individually by road atm.
>> This will never be possible

Have taken a look at NS code and there are a couple of interesting classes.
There's SegmentData class to store settings on a per prefab basis and SegmentDataManager to manipulate the data. With suitable use of GetActiveOptions and SetActiveOptions methods individual NS might be possible.
