### ISSUE TITLE
Drop down search

### ISSUE THREAD

**Issue by pkej** [ST-Apps/CS-ParallelRoadTool#14]
The drop down for selecting network to use in each slot can be extremely long, it should support search/sorting. For example, if I want a train track I should be able to select the drop down and start writing "t" + "r" etc. to filter the list of available networks. I think it also should return all networks that starts with "tr" (in this example) first and alphabetically, then those containing.

**Comment by ST-Apps** [comment]
I can't promise anything on this, but for now you can just select the network you need before clicking the "+" button.

**Comment by pkej** [comment]
That works very well 👍

**Comment by BadiBasso** [comment]
@ST-Apps Might be worthwhile to take a look at the UIFastList class from the Import/export PR. Has some nice features for displaying lists.

**Comment by ST-Apps** [comment]
@BadiBasso thanks but I went for a different route to make it work with current dropdowns, I don't want to mess with UI that much.

Updated (and fully working!) version tracked in [ISSUE-14-2](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-14-2) branch.
