### ISSUE TITLE
Position offset and height

### ISSUE THREAD

**Issue by pkej** [ST-Apps/CS-ParallelRoadTool#15]
It is possible to write alphabetical characters etc. in these two fields. For me I'd prefer that it shifted focus out of the field upon alphabetical input. Its been numerous times I want to move my viewport and instead I've been writing into these fields :)

**Comment by ST-Apps** [comment]
I'm not sure if it can be done because it depends on Unity3D's ui components, but I'll look into that.

**Comment by pkej** [comment]
I don't know Unity3D, but I googled a little, [could this be the solution](https://answers.unity.com/questions/18736/restrict-characters-in-guitextfield.html)?
