### ISSUE TITLE
Remember last used settings

### ISSUE THREAD

**Issue by pkej** [ST-Apps/CS-ParallelRoadTool#16]
After making a setup and restarting Cities: Skylines, in order to for example load new assets, I have to reconfigure my tool one more time. This will be less tedious if/when [Drop down search](https://github.com/ST-Apps/CS-ParallelRoadTool/issues/14) is added, but it would be a much appreciated feature to have.

**Comment by ST-Apps** [comment]
I was already thinking about the ability to store/load presets, but it won't be there in the first non-beta version.

**Comment by pkej** [comment]
That's okay, with the feature of selecting network first and then adding it to the list it solved my worst gripe. Now it's quicker to add up what's needed.

Great work. I'm going to test issue-18 version.

**Comment by BadiBasso** [comment]
@ST-Apps Have you had any progress on this? If not, I could take a look. The Move It! mod seems to have a nice basic load/save code implemented to start with.

**Comment by ST-Apps** [comment]
Yeah.
This could be related to ability to store/load presets (the last used settings can be a special case of preset).
If you could look into MoveIt mod would be great.

**Comment by BadiBasso** [comment]
All right then, I'll concentrate on this from now on.

**Comment by ST-Apps** [comment]
Sorry for the delay, here's yout branch: https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-16

Just keep on going, we'll review the hacky code together and eventually find a better solution :)
