### ISSUE TITLE
Automatically turn off CS-PRT when plopping stations etc.

### ISSUE THREAD

**Issue by pkej** [ST-Apps/CS-ParallelRoadTool#18]
When I plop my stations next to a road, the CS-PRT will plop all the extra roads that are set up.

**Comment by jvaruta** [comment]
Same thing with ploppable parks... the roads are placed parallel to the pedestrian paths.

**Comment by ST-Apps** [comment]
Just updated on Workshop, waiting for your feedback before closing this.

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-18](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-18) branch.

**Comment by pkej** [comment]
Works great. It's working well for me.

One thing I only tested today was plopping other networks, like water or power, and it plops the things marked in the PRT. I suggest that the PRT-window should be visible, as well as the icon, in those network modes, to alert the user of its function in those modes. It can really ruin a good layout if it is on and you don't have a visual clue.

I love it that I can use PRT for any network.

**Comment by pkej** [comment]
I tested with: Ploppable RICO, ploppable asphalt, surface painter tool and no issues.

I've tested placing health- and death care, police, fire, garbage, power buildings, water treatment, educational buildings, monuments, parks, and unique buildings. They all work as expected.

And I'm using it with these modules with no side effects:

### mods list ###

Hard Mode (ID=18446744073709551615)                         deactivated
Unlimited Money (ID=18446744073709551615)                   activated
Unlimited Oil And Ore (ID=18446744073709551615)             activated
Unlimited Soil (ID=18446744073709551615)                    activated
Unlock All (ID=18446744073709551615)                        activated
Decal Prop Fix (ID=767233815)                               activated
Sun Shafts (ID=933513277)                                   activated
Quay Anarchy (ID=650436109)                                 activated
Surface Painter (ID=689937287)                              activated
Daylight Classic (ID=530871278)                             activated
Clouds & Fog Toggler (ID=523824395)                         activated
Adaptive Prop Visibility Distance (ID=625608461)            activated
Dynamic Resolution (ID=812713438)                           activated
Tides (ID=1348627392)                                       activated
Precise Prop Positioning for Asset Creators (ID=1361644472) activated
Unlimited Trees Mod (ID=455403039)                          deactivated
UnlimitedOutsideConnections (ID=497033453)                  deactivated
Ploppable RICO (ID=586012417)                               activated
Network Skins (ID=543722850)                                deactivated
Resilient Owners (ID=820547325)                             activated
Ploppable Asphalt (ID=881291183)                            activated
Precision Engineering (ID=445589127)                        activated
Sharp Junction Angles (ID=553184329)                        activated
Procedural Objects 1.5.2 (ID=1094334744)                    activated
OSM Importer (ID=771161159)                                 deactivated
Network Extensions 2 (ID=812125426)                         activated
Network Tiling (ID=1274199764)                              activated
Zoning and Districts Co-viewer (ID=443904654)               activated
Topographic Lines Toggle (ID=877748783)                     activated
Cash on Demand (ID=1367444256)                              activated
Loading Screen Mod (ID=667342976)                           activated
AutoBudget V2 (ID=638764569)                                activated
Traffic Manager: President Edition [1.10.7] (ID=583429740)  activated
More Beautification (ID=505480567)                          activated
Prop Line Tool (ID=694512541)                               activated
TLM Reborn 9.0.2 (ID=1312767991)                            activated
Touch This! Tool 2.0.1 (ID=1393797695)                      activated
Klyte Commons 1.1.2 (ID=1312735149)                         activated
81 Tiles (Fixed for C:S 1.2+) (ID=576327847)                activated
Parkify r1.0.2 (ID=1393452031)                              activated
Better bulldoze Tool (ID=417965096)                         activated
Cinematic Camera Extended 0.5.1 (ID=785528371)              activated
Tree Snapping (ID=869134690)                                activated
Prop Snapping (ID=787611845)                                activated
Move It! 2.1.2 (ID=766190099)                               activated
Extra Landscaping Tools (ID=502750307)                      activated
Prop & Tree Anarchy (ID=593588108)                          activated
Fine Road Tool 1.3.7 (ID=651322972)                         activated
Prop Precision 1.0.1 (ID=791221322)                         activated
Shicho (ID=1383456057)                                      activated
Advanced Toolbar (ID=563229150)                             activated
Find It! 1.5.3 (ID=837734529)                               activated
Fine Road Anarchy 1.3.5 (ID=802066100)                      activated
[BETA] Parallel Road Tool 0.0.1 b-dev (ID=1400711138)       activated
Control Building Level Up (ID=1403136223)                   activated

**Comment by pkej** [comment]
Works with Find It! as well. The PRT window appears when selecting network items there.

**Comment by pkej** [comment]
> Same thing with ploppable parks... the roads are placed parallel to the pedestrian paths.

The PRT tool shows up on the toolbar, and the PRT window pops up, alerting me to the fact that it is on.  Try checking with the latest release and see if that's working for you as well @jvaruta

**Comment by jvaruta** [comment]
Seems to be fixed now.. I couldn't recreate the problem.. Thank you
