### ISSUE TITLE
Incompatible with Network Skins after the last update

### ISSUE THREAD

**Issue by kaminogi** [ST-Apps/CS-ParallelRoadTool#19]
I found I can't change "Street Lights" today.
Yesterday I was able to change.

Then I thought there was something to do with ParallelRoadTool's update, I deactivated once. Then Network Skins works normally.

In this session, I haven't opened ParallelRoadTool's window and not used.

Could you check the recent changes around road props?

**Comment by ST-Apps** [comment]
Duplicate of #12
