### ISSUE TITLE
Wider (or sizeable) window

### ISSUE THREAD

**Issue by pkej** [ST-Apps/CS-ParallelRoadTool#20]
Hi, on my computer the PRT windows could be wider to accommodate some of the longer text names. However, I understand things can become too big for some screens and resolutions so the perfect solution would be a window that could be resized and let the name dropdowns on the left be the flexible part of the window.

**Comment by DaEgi01** [comment]
an alternative would be to show the long names in a tooltip although that also has some usability issues.

**Comment by pkej** [comment]
It took Microsoft around 20 years to fix the cross reference dialog, it used to be non rescalable and modal. Don't be Microsoft :)

I'm joking, other stuff should have higher priority, like the features mentioned in the modules Steam-page.
