### ISSUE TITLE
Show the overlay for all roads prior to placement

### ISSUE THREAD

**Issue by DaEgi01** [ST-Apps/CS-ParallelRoadTool#22]
I'd love to see the blue overlay for all roads that will be placed prior to placement.
Currently only the overlay for the "guide road" is shown which makes it difficult to use the tool in tight environments.

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-22](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-22) branch.

**Comment by ST-Apps** [comment]
Just released a new updated in the Workshop that fixes this issue, waiting for your feedback.

**Comment by DaEgi01** [comment]
looks good even with the overlapping. much better like that.
