### ISSUE TITLE
Allow selecting the side where roads are placed in relation to the guide road

### ISSUE THREAD

**Issue by DaEgi01** [ST-Apps/CS-ParallelRoadTool#23]
Currently all PRT "extensions" are left of the guide road.
I'd love to be able to decide where the guide road is in that order.
example:
road
guide road
road
road

expectation: one road should be placed to the left, two to the right of the guide road.

my suggestion is to let the line that is "same as selected      +" represent the guide road.

instead of the + sign there should be two arrows ... one up and one down.
the up arrow places roads to the left of the guide road.
the down arrow places roads to the right of the guide road.
That is in relation to the drag direction.

the guide road should have a visual indicator so that a user knows if "up" is mapped to "left" or "right".
something like 
"> Guide Road      ^v"

**Comment by DaEgi01** [comment]
ok ... negative offset does the trick so I was just to dump to see it ;)
in that case only the usability improvements are relevant.

**Comment by ST-Apps** [comment]
Related to #17, will probably come somewhere in the future.
