### ISSUE TITLE
Third road swirls on lefthand drive roads

### ISSUE THREAD

**Issue by rsb10961** [ST-Apps/CS-ParallelRoadTool#38]
Hi, 
excellent tool!  This is the same as #7. When I add a third road, it "swirls" over the other two:
![image](https://user-images.githubusercontent.com/41256642/42732221-a2a6d902-881d-11e8-9fa6-9eeeb5656a63.png)
Could some other mod be interfering with PRT?
Thnx.
RB

**Comment by BadiBasso** [comment]
Noticed in my tests that swirling happens wwith every other additional road, ie 2nd, 4th, 6th etc.
Have found a preliminary fix to eliminate swirling but it rose an issue with snapping :(
Still investigating...

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-38](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-38) branch.

**Comment by ST-Apps** [comment]
@BadiBasso I forgot to link the branch, but I started working on this yesterday and got to your very same situation. Node position is now correct, but it doesn't snap.

If you need it, here's a quick log snippet that highlights the issue:

> [Parallel Road Tool 1.0.2] [CreateSegment] [START] Using old node from previous iteration 24478 instead of the given one 23377
> [Parallel Road Tool 1.0.2] [CreateSegment] [START] Start node (354.8, 226.0, -470.1) becomes (339.3, 226.0, -473.9)
> [Parallel Road Tool 1.0.2] [CreateSegment] [END] (335.9, 226.1, -392.4) --> (320.3, 226.1, -396.1) | isEnteringSlope = False | invert = False | isSlope = False
>  
> [Parallel Road Tool 1.0.2] [CreateSegment] [START] (354.8, 226.0, -470.1) --> (323.7, 226.0, -477.7) | isLeftHand = True | invert = True  | isSlope = False | startNode = 25198 | endNode = 23377
> [Parallel Road Tool 1.0.2] [CreateSegment] [END] (335.9, 226.1, -392.4) --> (304.8, 226.1, -399.9) | isEnteringSlope = False | invert = True | isSlope = False
>  
> [Parallel Road Tool 1.0.2] [CreateSegment] [START] Using old node from previous iteration 17757 instead of the given one 23377
> [Parallel Road Tool 1.0.2] [CreateSegment] [START] Start node (354.8, 226.0, -470.1) becomes (308.2, 226.0, -481.4)
> [Parallel Road Tool 1.0.2] [CreateSegment] [END] (335.9, 226.1, -392.4) --> (289.2, 226.1, -403.7) | isEnteringSlope = False | invert = False | isSlope = False
>  
> [Parallel Road Tool 1.0.2] [CreateSegment] [START] (354.8, 226.0, -470.1) --> (292.6, 226.0, -485.2) | isLeftHand = True | invert = True  | isSlope = False | startNode = 25198 | endNode = 23377
> [Parallel Road Tool 1.0.2] [CreateSegment] [END] (335.9, 226.1, -392.4) --> (273.7, 226.1, -407.5) | isEnteringSlope = False | invert = True | isSlope = False

The key should be `invert = True` because it works when `invert = False`.

**Comment by ST-Apps** [comment]
Ok, no, situation is even worse than what I thought. Reversing roads and curves are not working anymore. This will take a little bit than expected.

**Comment by BadiBasso** [comment]
I think I got it...
Have tested with one ways and highways. Everything seems to be nice :)

Will place a PR after cleaning up….

**Comment by ST-Apps** [comment]
@rsb10961 can you please switch to the BETA version and report back to see if it has been fixed for you? Thanks.

**Comment by rsb10961** [comment]
Looks good to me guys!
![image](https://user-images.githubusercontent.com/41256642/43095827-59d38996-8eb7-11e8-8ce4-a8c837b61d20.png)
![image](https://user-images.githubusercontent.com/41256642/43095839-67231382-8eb7-11e8-9c83-bf48b24f9444.png)

**Comment by BadiBasso** [comment]
Looks promising! Could you please try with more roads (4 or more) mixed with oneways and/or highways?
Just to verify that nodes connect correctly.
BTW additional roads are placed on right side in left hand drive now. More logical IMO

**Comment by rsb10961** [comment]
Yep, the nodes do connect correctly, as far as I can make out.
![image](https://user-images.githubusercontent.com/41256642/43097999-179dc5d0-8ebe-11e8-9836-695f83eb129b.png)

**Comment by BadiBasso** [comment]
Great! Thanks for your help!
