### ISSUE TITLE
Significant FPS loss in some scenarios

### ISSUE THREAD

**Issue by ST-Apps** [ST-Apps/CS-ParallelRoadTool#39]

**Comment by Owlchemist** [comment]
I was auditing my mods today, trying to isolate performance loss. I ended up here! With my usual set of popular mods I was at 60 fps (v-sync) but with this mod enabled it dropped to around 40 fps. And I tested with a blank, fresh map. Running on windows 10.

**Comment by Videonauth** [comment]
Can confirm the FPS loss, for me it was on my already existing highly detailed map from 15 FPS down to 6 which is at this stage significant, disabling this mod returned it back to 14-16 (15).

Specs: GTX 750 Ti 4 GB, i5-4690, Ubuntu Linux , 128 GB RAM 
Game specs: actually used Assets 12712, 89 GB RAM usage

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-39](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-39) branch.

**Comment by ST-Apps** [comment]
Just released a new [beta on the Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1400711138).
Can you guys please unsub from stable one and see if this version is better?
With this one I have almost the same FPS as without the mod (100 fps without mod, 96 with it).

Waiting for your feedback!

**Comment by Videonauth** [comment]
Can confirm, the Beta version is far better on the FPS, on my game I loose about 2 frames out of the already low FPS rate due to detailing. So whatever you did improved the frame-rate on my side from 6 to 14 which is not far of what I have without the mod.

**Comment by ST-Apps** [comment]
Nice, waiting for @Owlchemist then.
I'm not releasing this yet as I introduced a little bug with tutorial window (sometimes you need to press twice to show it) and I'd like to fix it.

I'll let you guys know when I'll move the fix to stable version.

**Comment by Videonauth** [comment]
No Problem, I will stay on Beta for now then :)

**Comment by Owlchemist** [comment]
I am reporting similar results. On a new map, I get 50-52 fps without the beta, and 48-50 with it.

**Comment by ST-Apps** [comment]
Thanks for your feedback.
The fix will be included in the next stable release.
