### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by TheGoldenMan99** [ST-Apps/CS-ParallelRoadTool#41]
I translated the file into German. Everything should work but some one looking over it once wouldn't be bad.
PS: I have never used Github before so hopefully the post is in the right category and everything uploaded correctly (XML wasn't supported so I had to upload it as TXT)
[de.txt](https://github.com/ST-Apps/CS-ParallelRoadTool/files/2198931/de.txt)

**Comment by ST-Apps** [comment]
Hi and thanks.
Do you have a Steam profile link (or another link) that you'd like to have in mod's description?

**Comment by Fungopus** [comment]
[de_1_2.txt](https://github.com/ST-Apps/CS-ParallelRoadTool/files/2215370/de_1_2.txt)

Hi, I corrected some typing errors and changed the words "Reduziere" to "Verkleinere" at DECREASEOFFSETPOSITION.

**Comment by ST-Apps** [comment]
Thank you both, adding it now!
