### ISSUE TITLE
Generate thumbnails and visual guide for Steam Workshop

### ISSUE THREAD

**Issue by ST-Apps** [ST-Apps/CS-ParallelRoadTool#5]

**Comment by CarlTheCroissant** [comment]
I can help with the visual guide. Are there any other features that need to be included other than how to change spacing, how to add roads, and how to reverse roads?

**Comment by ST-Apps** [comment]
Hi there and thanks.
I think that something that is not clear enough is that, when you click add, the current selected road is the one being added. This means that you're not forced to endlessly scroll the dropdown but you can simply remove the road, select a new one and click the add button.

Another thing worth mentioning is that spacing may be negative too, allowing you to build on both sides of your current road.

**Comment by ST-Apps** [comment]
I like it, thanks!
If you're familiar with GitHub, would you mind doing a PR after adding them to the workshop folder?

**Comment by CarlTheCroissant** [comment]
I've never used GitHub before, but I think I can figure out what I'm doing.
When I try to upload filed to the workshop folder, it says I need push access.

**Comment by ST-Apps** [comment]
PR #11

**Comment by ST-Apps** [comment]
Thank you for your help!
