### ISSUE TITLE
Sorting by name

### ISSUE THREAD

**Issue by kacper1703** [ST-Apps/CS-ParallelRoadTool#64]
I have CS language set to Polish and the road names are not sorted alphabetically:

<img width="286" alt="screen shot 2018-09-01 at 09 12 40" src="https://user-images.githubusercontent.com/12765428/44943478-3db26a00-adc7-11e8-9724-ee17a080ce91.png">

Is there a way to sort them by localized name or are the localizations stored completely else and not easily accessible?

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-64](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-64) branch.

**Comment by ST-Apps** [comment]
I just updated BETA version with networks sorting, please let me know if it works for you.
