### ISSUE TITLE
Swedish Translation

### ISSUE THREAD

**Issue by Lemshimmer** [ST-Apps/CS-ParallelRoadTool#66]
I'll happily translate the mod into swedish if neccesary.

**Comment by Abragus** [comment]
I would too.

**Comment by BadiBasso** [comment]
@Lemshimmer, @Abragus I trust that dev would be happy to have additional translations. Do you need instructions how to do it?

**Comment by Lemshimmer** [comment]
@badibasso
I do not know about @Abragus , but I would like some instructions. Also, my discord name is Lemshimmer1398#. I’m online there more often than here.

**Comment by BadiBasso** [comment]
@Lemshimmer All you need to do is to copy the en.xml file from Assets/Localizations, replace the appropriate strings in that file with localized versions, rename the file as se.xml (swedish locale)  and provide the localized file as PR (preffered method) or as an attachment to this issue.
