### ISSUE TITLE
Ctrl+P doesn't work.

### ISSUE THREAD

**Issue by rmjohnson144** [ST-Apps/CS-ParallelRoadTool#69]
I can't get the Ctrl+P to bring up the menu and it seems to lock up the acreen until I hit Ctrl+P again.  The button in the road menu didn't work either

I restarted and used the button first, and t worked.

I restarted again to check some setting in-game and it crashed with error report.

I don't use workshop.  well, I think I had CSL Music Mod installed iirc.
[error.zip](https://github.com/ST-Apps/CS-ParallelRoadTool/files/2587078/error.zip)

**Comment by ST-Apps** [comment]
Just took a quick look, it doesn't seem related to my mod but I'll try to investigate it as soon as I can.
