### ISSUE TITLE
Start (or end) nodes' offset is on the wrong side

### ISSUE THREAD

**Issue by Dannypan** [ST-Apps/CS-ParallelRoadTool#7]
I tried to draw some roads with your mod and this happened! Not sure what caused it, I'm afraid

![image](https://user-images.githubusercontent.com/39864044/40880119-2184c8ca-66a3-11e8-9015-7361ecd48fe4.png)

**Comment by ST-Apps** [comment]
@BadiBasso thanks, I guess it's solved then but I'll wait for his confirmation before closing the issue.
By the way, were you involved in PoGo-UWP by any chance? Your name sounds familiar to me.

**Comment by BadiBasso** [comment]
Hehe. Yes I was 😃
Been closely watching your efforts on this since your post on Reddit.
I have a few thoughts brewing about this mod, and might participate at some point, if you don't mind 😃

**Comment by ST-Apps** [comment]
That's so weird, I started (and left) PoGo-UWP almost 2 years ago and we find each other here in a completely unrelated project lol
I'd be glad to have you on board here :)

@Dannypan sorry for the spam, I'm just waiting for your confirmation before closing the issue :)

**Comment by Dannypan** [comment]
Sorry for making you wait! It's all working for me now.

Dunno if you still need it, but here's my output log (too big for pastebin I'm afraid)

[output_log.txt](https://github.com/ST-Apps/CS-ParallelRoadTool/files/2066303/output_log.txt)

**Comment by ST-Apps** [comment]
There's no need to apologize :)
If everything's fine we can close this, thanks for your collaboration!
