### ISSUE TITLE
Stopped working with latest update

### ISSUE THREAD

**Issue by Nijomi** [ST-Apps/CS-ParallelRoadTool#76]
The tool has ceased to work with the latest update today.

**Comment by Marquillotuca89** [comment]
I don't think we'll be getting an update. It's such a shame!

**Comment by ST-Apps** [comment]
I'm considering getting back to actively develop this one actually.
I did a quick test and it worked for me, do you have more details on this issue?

**Comment by Marquillotuca89** [comment]
> I'm considering getting back to actively develop this one actually.
> I did a quick test and it worked for me, do you have more details on this issue?

Well, for me, what happens is that sometimes, the tool just stops working. For example:  I'm building a highway, I toggle the tool on/off several times and randomly, the icon just stops showing and after that, I can't toggle on the tool again even with Ctrl +P. 
A lot of people are reporting similar bugs on Steam Workshop.

**Comment by Marquillotuca89** [comment]
Today, I experimented the bug. I'm uploading the output log. 

[output_log.zip](https://github.com/ST-Apps/CS-ParallelRoadTool/files/4467185/output_log.zip)

**Comment by ST-Apps** [comment]
Duplicate of #69
