### ISSUE TITLE
Tunnel exit not working

### ISSUE THREAD

**Issue by ST-Apps** [ST-Apps/CS-ParallelRoadTool#78]
*Wrathserker*

> Theer is a bug when using paralell roads underground u cnat make tunnel exits cause they get twisted and flipped all weirdly.

Possibly related to #3?

**Comment by andyundso** [comment]
Can confirm there is still something bugged in this area.

Built a tunnel and had to change some segments. When trying to connect the segment manually created with the one from ParallelRoad, it created a tunnel entrance regardless how "deep" tunnel is.

![20210516235817_1](https://user-images.githubusercontent.com/7010698/118414090-f7021c80-b6a2-11eb-80c0-66b57dda0208.jpg)
