### ISSUE TITLE
Analysis on conflicting mods / Sunset Harbor

### ISSUE THREAD

**Issue by CityGecko** [ST-Apps/CS-ParallelRoadTool#79]
Hi Stefano

I played today a bit around to nail down the mod, which may cause a conflict. In earlier times I always had issues with Klytes mods, thus need to disable those when editing a map or once I feel requirement to place parallel roads in my savegame.

So here is what I did today:
In general, Parallel Road Tool seems working with in Editor and in Game und the following test conditions:

Disable all mods, then enable Parallel Road Tool in Content Manager.
Minimum additional enabled mods successfully tested in Editor and Game:
https://steamcommunity.com/sharedfiles/filedetails/?id=1844440354] Klytes Fine Road Anarchy
https://steamcommunity.com/sharedfiles/filedetails/?id=1645781000 Elektrix Road Tools

If subscribed to Klytes Fine Road Tools, do not enable it in Content Manager. It will break the Parallel Road Tool. If deactivated, Parallel Road Tools works fine. Once activated, the GUI does not show and in editor there was only one road to be dragged. 

https://steamcommunity.com/sharedfiles/filedetails/?id=1844442251 Klytes Fine Road Tools 2

Workaround: Disable Fine Road Tools in Content Manager during editing parallel roads, afterwards re-enable.

Once I tested the above three mods, I started to activate my other mods, which I am subscribed to.

Here is the list with all mods activated and deactivated.
Sucessful maximum test with enabled mods successfully tested in Editor and Game:
Hard Mode (ID=18446744073709551615)                         deactivated
Unlimited Money (ID=18446744073709551615)                   activated
Unlimited Oil And Ore (ID=18446744073709551615)             activated
Unlimited Soil (ID=18446744073709551615)                    activated
Unlock All (ID=18446744073709551615)                        activated
Advanced Vehicle Options 1.9.2 (ID=18446744073709551615)    activated
Decal Prop Fix (ID=767233815)                               activated
Empty It! (ID=1661072176)                                   activated
Precision Engineering (ID=445589127)                        activated
Surface Painter (ID=689937287)                              deactivated
AutoLineColor Redux (ID=1415090282)                         activated
Forest Brush (ID=1658679290)                                activated
Network Dump Tools (ID=1845697704)                          deactivated
Zoom It! (ID=1756089251)                                    activated
Rebuild It! (ID=1656549865)                                 activated
Optimised Outside Connections (ID=1721492498)               activated
Watch It! (ID=1643902284)                                   activated
Hide It! (ID=1591417160)                                    activated
Bulldoze It! (ID=1627986403)                                activated
Redcomet's Municipal Sound Pack (ID=591137516)              activated
Purchase It! (ID=1612287735)                                activated
Show It! (ID=1556715327)                                    activated
Demand Master (ID=409776678)                                activated
American Traffic Lights (ID=694123443)                      activated
Prop Snapping (ID=787611845)                                activated
Prop & Tree Anarchy (ID=593588108)                          activated
Tram Station Track (ID=707497031)                           activated
Touch This! Tool 3 (ID=1393797695)                          activated
Unlimited Trees Mod (ID=455403039)                          activated
Tree Movement Control (ID=1388613752)                       activated
Map Editor Tunnels Enabler (ID=645390478)                   activated
Improved Wind Simulation (ID=627096876)                     activated
Parkify r1.0.3 (ID=1393452031)                              activated
Ragnarok (ID=811352708)                                     activated
Find It! 1.5.4 (ID=837734529)                               activated
Extra Landscaping Tools (ID=502750307)                      activated
Daylight Classic (ID=530871278)                             activated
Cash on Demand (ID=409171141)                               activated
American Roadsigns 2.2.0 (ID=690066392)                     activated
Ambient Sounds Tuner (ID=818641631)                         activated
Bee's North American Sound Pack (ID=939566479)              activated
Airport Roads 1.3.7 (ID=465127441)                          activated
AST: KRA Sound Pack (ID=618536610)                          activated
Save Our Saves (ID=529129546)                               deactivated
Mini FPS Booster 1.0 (ID=1938493221)                        activated
Building Theme: European Suburbia Decorated (ID=1903967441) activated
Enhanced District Services 1.0.18 (ID=1922400472)           activated
Railway Replacer (ID=1530376523)                            activated
Pedestrian Crossings (ID=427258853)                         activated
DAS v1.2.0 (ID=2013398705)                                  deactivated
Parallel Road Tool 1.3.0 (ID=1440928803)                    activated
Harmony 2.0.0.9 (ID=2040656402)                             activated
Custom Animation Loader (CAL) (ID=1664509314)               activated
Transparency LOD Fix + Cloud Assets Enabler (ID=922939393)  activated
Emergency Lights Manager V2 (ID=2053661585)                 activated
Trailer Variation Loader (ID=1552053911)                    activated
Extra Vehicle Effects (ID=815103125)                        activated
Vehicle Effects 1.8.1b (ID=780720853)                       activated
Prefab Hook (ID=530771650)                                  activated
Broken Node Detector 0.4 (ID=1777173984)                    deactivated
ModTools (ID=450877484)                                     deactivated
CSL Show More Limits (ID=531738447)                         deactivated
TM:PE 11.3.1 LABS (ID=1806963141)                           activated
Improved Public Transport 2 [r5.0.3] (ID=928128676)         activated
Klyte's Fine Road Anarchy 2.0.2 (ID=1844440354)             activated
Customize It! Extended (ID=1806759255)                      activated
Resize It! (ID=1577882296)                                  activated
Elektrix's Road Tools (ID=1645781000)                       activated
Sort Mod Settings (ID=973512634)                            activated
Improved Content Manager (ID=814498849)                     activated
Network Skins 2 (ID=1758376843)                             activated
Auto Repair (ID=2034713132)                                 activated
Sequence Logger (ID=2018193885)                             deactivated
Achieve It! (ID=1567569285)                                 activated
More Network Stuff (ID=512314255)                           activated
Extra Train Station Tracks (ID=515489008)                   activated
Rebalanced Industries (ID=1562650024)                       activated
Sub-Buildings Tabs (ID=608517757)                           activated
Klyte's Fine Road Tool 2.0.4 (ID=1844442251)                deactivated
Move It 2.7.1 (ID=1619685021)                               activated
Loading Screen Mod (ID=667342976)                           activated

Hopes this helps you a bit. You may also try to connect to Aubergine18 and Klyte for a joint approach of fixing things.

**Comment by CityGecko** [comment]
Not on Reddit, but here or on Discord or just Steam. Happy to join your beta, if you need someone. Also suggest to contact / liaise with Aubergine18.

**Comment by ST-Apps** [comment]
Closing because we discussed this on Steam and it seems to be working now.
