### ISSUE TITLE
Not working properly in left hand traffic

### ISSUE THREAD

**Issue by kaminogi** [ST-Apps/CS-ParallelRoadTool#8]
When I select "Left-hand Traffic" at the beginning, this mod won't works well like this:

![screenshot 367](https://user-images.githubusercontent.com/4347354/40887573-dd7ea3ce-6785-11e8-9c14-d4b2e6bee32a.png)

I used custom railroads in this picture, but I tried vanilla roads and got same result.

Since I turned off  "Left-hand Traffic", seems working properly.

![screenshot 368](https://user-images.githubusercontent.com/4347354/40887576-df76352a-6785-11e8-93fd-06ee9c8dea2d.png)

Can you fix this?

If you need more information, please tell me.
Thank you.

**Comment by ST-Apps** [comment]
Here's something I completely forgot to test, thanks for pointing it out.
Probably related to #7.

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-8](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-8) branch.

**Comment by kaminogi** [comment]
Thank you for your prompt attention!

The bug completely fixed in the latest version.

Good job. 👍

**Comment by ST-Apps** [comment]
Nice, I'm closing this then :)
