### ISSUE TITLE
Limiting Networks in Dropdown

### ISSUE THREAD

**Issue by CityGecko** [ST-Apps/CS-ParallelRoadTool#83]
Not sure if to be considered an issue. PRT will pick up all kind of Networks. This includes e.g. the paths for planes, ships etc. I would suggest to remove them and only allow road, rail, the common stuff and not the "delicate" like the above paths, connections, lines. 

Here's the link for all items, which I think should be not accessable: https://imgur.com/a/f66fJPq
(selection, mabye not complete)

**Comment by ST-Apps** [comment]
I understand what you mean, but what are the downsides of having those networks available?

I did some quick research, and hiding those networks may require more changes than I thought, so I want to be 100% sure that this is something really needed.

**Comment by CityGecko** [comment]
Actually not an issue for me, but may could confuse unexperienced user by choosing wrong network and then break their game/map (with those paths eventually).
