### ISSUE TITLE
Road bugged out

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [ST-Apps/CS-ParallelRoadTool#87]
I cannot really describe it well so I well let the picture speak for itself:
[Photo](https://imgur.com/GWgprXp)

I built this highway normally with the paralell road mod,and when I came back later, it was bugged out like this. There appears to be two "parts", I have been able to delete one of them, this one though I am not able to delete. I am able to select it with the MoveIt mod.

**Comment by ST-Apps** [comment]
Can you please tell me which configuration you were using? I think there might be an issue with certain roads.

**Comment by svhnl** [comment]
> Can you please tell me which configuration you were using? I think there might be an issue with certain roads.

I am using the vanilla 3-lane highway with soundbarrier. I did just discover I switched from the beta version to the stable version, could that be the problem?
