### ISSUE TITLE
Mod's window seems to extend passed visible part, blocking cursor from placing road.

### ISSUE THREAD

**Issue by CarlTheCroissant** [ST-Apps/CS-ParallelRoadTool#9]
The window for the mod seems to have a section that goes passed the visible part. This prevents you from drawing any roads in this area while the window is open. This image has that part outlined in roads.
![20180605101541_1](https://user-images.githubusercontent.com/39924268/40985792-766853da-68aa-11e8-9305-8140bfab7f57.jpg)

**Comment by ST-Apps** [comment]
Tracking it in [ISSUE-9](https://github.com/ST-Apps/CS-ParallelRoadTool/tree/ISSUE-9) branch.

**Comment by ST-Apps** [comment]
I just updated Workshop's version, can you please check if it has been solved for you?

**Comment by CarlTheCroissant** [comment]
It's fixed!
