### ISSUE TITLE
Wrong road cost

### ISSUE THREAD

**Issue by ST-Apps** [ST-Apps/CS-ParallelRoadTool#93]
_From B4nditOo on Steam_

> Cost of highway is astronomical. This mod used to work for me one year ago, now that I've came back and had to update some mods to newer versions (previous one were no longer maintained, like TM:PE, Fine Road Tools, Fine Road Anarchy and some others), it no longer works - the cost of things is waaayyy too high:
> https://imgur.com/a/x4ZoeCr

**Comment by hammylikey** [comment]
As a bit of extra info, it happens regardless of the road/track you use as the source. The cost of a short amount of rail track goes from about 500 to north of 10-15k

**Comment by db48x** [comment]
I've noticed that the prices are wrong in an interesting way:

12u length: https://steamcommunity.com/sharedfiles/filedetails/?id=2352066994

13u length: https://steamcommunity.com/sharedfiles/filedetails/?id=2352067104

Some aspects of the price (such as slopes) accumulate for every segment, but the majority of the cost only goes up ever 12u.

On the other hand, the code that calculates the price is very straight-forward and looks obviously correct, assuming that adding and removing detours is working correctly.
